language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - libgmp-dev
      - libffi-dev
env:
  - DJANGO=1.11 WEBTHREE=4.9
  - DJANGO=2.0 WEBTHREE=4.9
  - DJANGO=2.1 WEBTHREE=4.9
  - DJANGO=2.2 WEBTHREE=4.9
matrix:
  include:
    - python: "3.6"
      env: TOXENV=flake8
install:
  - pip install tox-travis codecov
script:
  - tox
after_success:
  - codecov
