language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.5
      env: TOXENV=flake8
install:
  - pip install -r requirements.txt
  - pip install tox-travis
script:
  - tox
